### ISSUE TITLE
A* with JPS

### ISSUE THREAD

**Issue by NoiSek** [lowlighter/astar#1]
Thanks for posting this, I'm a fan of your API! This looks much more flexible than most of the other pathfinding libs I've seen out there, and I'm actually going to switch away from the library that I've been using [(bgrins/javascript-astar)](https://github.com/bgrins/javascript-astar) and use yours instead.

Is there any chance that you would consider implementing Jump Point Search? I'm in a situation where performance is a huge concern, and I believe JPS would help alleviate some of that.

If you aren't already aware,

[Demonstration (use dropdown)](https://anttilip.github.io/pathfinding-visualizer/)
[Explanation 1](https://harablog.wordpress.com/2011/09/07/jump-point-search/)
[Explanation 2](https://zerowidth.com/2013/05/05/jump-point-search-explained.html)

**Comment by lowlighter** [comment]
Hi ! Thanks for your input !
I'm going to check what can be done for it :)
Hopefully it'll be implemented soon !

**Comment by lowlighter** [comment]
It's almost done, but it seems that there a still some issues with nodes never reached. 
This should be fixed this week.

Usage will be as below :
```javascript
astar.path(start, goal, {jps:true})
```

**Comment by lowlighter** [comment]
Done !
See it in action [here](https://lowlighter.github.io/astar/demo/) !
